### ISSUE TITLE
Image Viewer doesn't seem to work with uBlock Origin

### ISSUE THREAD

**Issue by GreatestFool** [friendlyanon/GelbooruEnhancement#10]
Image Viewer shows the image while loading, but once it is loaded it disappears and all that's left is a white background. Can be fixed by disabling it temporarily, or whitelisting gelbooru.

**Comment by friendlyanon** [comment]
Yes, there are some EasyList rules that block the loaded images, nothing I can do about this, you have to make an exception rule that targets `body > #slide[data-id]`, this CSS rule will always target the element displaying the image and will never change
