### ISSUE TITLE
Not showing full images

### ISSUE THREAD

**Issue by Yoposoc** [friendlyanon/GelbooruEnhancement#11]
It seems like the image viewer is broken. The thumbnail-quality image shows up full-screen sized for a second, then just white. The full image never comes up. The image viewer interface seems like it's loading up fine.

**Comment by friendlyanon** [comment]
Is your adblocker blocking the images by chance?

**Comment by Yoposoc** [comment]
idk what I did, but it's working now. The adblocker was only blocking trafficjunky.

**Comment by Yoposoc** [comment]
Ok, never mind. I'm getting this problem in sankakucomplex and it doesn't seem to be working.

**Comment by friendlyanon** [comment]
I recommend using uBlock Origin or uMatrix for blocking ads, I know those do not interfere with this image viewer script.

**Comment by Yoposoc** [comment]
I am in fact using uBlock Origin.

**Comment by Yoposoc** [comment]
![image](https://user-images.githubusercontent.com/2718371/47260265-d59a0f00-d46c-11e8-92c1-d0f745d26e01.png)
This is what ublock origin shows me on sankakucomplex

**Comment by friendlyanon** [comment]
I have turned on every single ruleset except uBlock experimental and a few regional ones and I still do not get a rule that blocks the image. Refresh the page, click the icon to the right of the eyedropper, try opening an image and see what is being blocked.

**Comment by Yoposoc** [comment]
Ok, well now I just see the thumbnail-quality picture in full-window size.

What I see from the ublock origin is this
![image](https://user-images.githubusercontent.com/2718371/47264776-c26d5a80-d4d1-11e8-8255-c3ff2d6ce971.png)
This afr thing is blocked by Easylist
