### ISSUE TITLE
Images load but are invisible

### ISSUE THREAD

**Issue by sanitysama** [friendlyanon/GelbooruEnhancement#14]
Images don't appear in the image viewer when I click on them. They load I just can't see them. I also can't click the image viewer away, I don't know where to click.  If I disable the image viewer script, endless scroll will load all pages of list results, and the thumbnails will load in a vertically cascading list. If I leave image viewer enabled endless scrolling works as intended, but I have to middle click thumbnails to keep the image viewer from opening.

Using Firefox Quantum 63.0.3. I'm in a 3440x1440 ultrawide viewspace if that matters, but I resized my browser to a smaller window and that didn't change any behavior. No errors show up in the browser console.

**Comment by cafrew** [comment]
I have the same problem as yours.
However I managed to fix it. By disable uBlock Origin (an extension for blocking ads)

If there is other ad blocker it's very suggested to disable it.

**Comment by sanitysama** [comment]
That seemed to be the cause of the issue, I looked into seeing if there's a way to prevent it with ublock without turning ublock off, but there's an easylist filter that wants to block all blobs from gelbooru.

**Comment by gitshit** [comment]
Adding `gelbooru.com#@#[src*="blob:"]` to filters in ublock origin overrides easylist and fixes the problem without disabling ad blocking entirely.

**Comment by sanitysama** [comment]
Thanks for the solution. I'd been trying to figure out this problem for a while.
