### ISSUE TITLE
Gelbooru endless Scroll broken

### ISSUE THREAD

**Issue by BlayZin** [friendlyanon/GelbooruEnhancement#2]
I don't know how you wanted the Script to look like in Action but for me it looks like broken: http://i.imgur.com/EvTg5Km.jpg

Is it supposed to show only one Picture/row?

**Comment by friendlyanon** [comment]
Gelbooru changes a lot with their responsive layout changes, so hopefully they'll settle for now. Also, I didn't really test Endless Scroll on its own, but only along with Image Viewer that injects styles to kind of fix the layout, i.e. make it look like before.
