### ISSUE TITLE
Gelbooru broken again

### ISSUE THREAD

**Issue by BlayZin** [friendlyanon/GelbooruEnhancement#4]
Sorry for posting again but Gelbooru added some weird Lazyload Javascript for Thumbnails and the Thumbnails won't load after Page 1.

**Comment by friendlyanon** [comment]
Already fixed with 8098ecc and 6346886

**Comment by BlayZin** [comment]
Not really. For me atleast. Although I use both Scripts it still looks like this: https://i.imgur.com/3iDtfPx.jpg

**Comment by friendlyanon** [comment]
fix't
They keep changing names. Current solution should figure out the thumbnail URL by itself now
