### ISSUE TITLE
image viewer bug with ublock

### ISSUE THREAD

**Issue by wongsaraf** [friendlyanon/GelbooruEnhancement#9]
Using ublock with easy list enabled will not render any image after it finished loading the image file.
Happen when used on Gelbooru site, sankakucomplex works fine.

Browser Firefox 57.0.4 64bit
moz-extension://56c64ef7-e9cd-4f64-bd9b-a916d32ce797/asset-viewer.html?url=easylist
https://easylist.to/easylist/easylist.txt

**Comment by friendlyanon** [comment]
Can't reproduce, I'm using AdNauseam with latest block lists.

I recommend using uMatrix, uBlock Origin or AdNauseam instead of uBlock.

**Comment by wongsaraf** [comment]
I'm using uBlock Origin with uMatrix.
Found the fix, disable cosmetic filtering on gelbooru will render the image normally again.
